### ISSUE TITLE
Parity version column is empty

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-netstats-agent#49] opened 2018-05-22 09:24 UTC
Sometimes when first started or after stop && start, parity version column is empty in the dashboard:
![selection-2018-05-22-12 08 30-001](https://user-images.githubusercontent.com/2278876/40352954-e94224a0-5db8-11e8-8142-72a0f6d13691.png)
Also `network` and `protocol` fields in the pop-up are equal to `null` in this case.

After some time the version number will appear

**Comment by Dzol** [comment] 2018-05-24 12:48
Hi @phahulin,

We can reproduce this + we have a solution.

The current Node/JS server won't send information to the dashboard until Parity has started otherwise there is no information listed for that node at all (i.e. there's no row for it in the node listing). Is this what you want from the Elixir agent too? Our current solution will send the _node name_ and display the node as "offline" on the dashboard. I thought this was helpful because the node is listed so that you know it exists but is shown "offline" so you know that as well.

**Comment by phahulin** [comment] 2018-05-24 13:14
It reproduces not only when parity is stopped, but also when it's running

**Comment by phahulin** [comment] 2018-05-24 13:17
Current solution with sending "offline" and empty row is fine, but it looks like when parity is started version remains empty.

**Comment by ferigis** [comment] 2018-05-24 13:30
we could reproduce the issue following this steps:

- start the Dashboard
- start the Agent
- start the Parity

The problem is when the agent connects to the Dashboard it sends the info but the data belonging to parity is not shown because the Parity node is not ready. Our fix is sending the data again when the Parity is up

**Comment by ferigis** [comment] 2018-05-25 13:06
closed by #51

**Closed as completed by ferigis** 2018-05-25 13:06 UTC
